/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package supermario;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class AppTest {
  private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
  private final PrintStream originalOut = System.out;

  @Before
  public void setUpStreams() {
    System.setOut(new PrintStream(outContent));
  }

  @After
  public void restoreStreams() {
    System.setOut(originalOut);
  }

  @Test
  public void test1(){
    App app = new App();

    String result = app.answerQuestion1().toUpperCase();

    String correct_answer = "YES";
    assertEquals(result, correct_answer);
  }

  @Test
  public void test2(){
    App app = new App();

    String result = app.answerQuestion2().toUpperCase();

    String correct_answer = "YES";
    assertEquals(result, correct_answer);
  }

  @Test
  public void test3(){
    App app = new App();

    String result = app.answerQuestion3().toUpperCase();

    String correct_answer = "YES";
    assertEquals(result, correct_answer);
  }

  @Test
  public void test4(){
    App app = new App();

    String result = app.answerQuestion3().toUpperCase();

    String correct_answer = "YES";
    assertEquals(result, correct_answer);
  }

  @Test
  public void test5(){
    App app = new App();

    String result = app.answerQuestion3().toUpperCase();

    String correct_answer = "YES";
    assertEquals(result, correct_answer);
  }

}
